---
- name: Create monitoring directories
  file:
    path: "{{ app_dir }}/{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - monitoring
    - monitoring/prometheus
    - monitoring/loki
    - monitoring/tempo
    - monitoring/alloy
    - monitoring/grafana
    - monitoring/grafana/provisioning
    - monitoring/grafana/dashboards

- name: Ensure Prometheus config paths are files
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ app_dir }}/monitoring/prometheus/prometheus.yml"
    - "{{ app_dir }}/monitoring/prometheus/alert.rules.yml"

- name: Copy Prometheus configuration
  copy:
    src: prometheus.yml
    dest: "{{ app_dir }}/monitoring/prometheus/prometheus.yml"
    owner: root
    group: root
    mode: "0644"

- name: Copy Prometheus alert rules
  copy:
    src: alert.rules.yml
    dest: "{{ app_dir }}/monitoring/prometheus/alert.rules.yml"
    owner: root
    group: root
    mode: "0644"

- name: Remove incorrect loki config directory if present
  file:
    path: "{{ app_dir }}/monitoring/loki/config.yml"
    state: absent

- name: Copy Loki configuration
  copy:
    src: loki.yml
    dest: "{{ app_dir }}/monitoring/loki/config.yml"
    owner: root
    group: root
    mode: "0644"

- name: Remove incorrect tempo config directory if present
  file:
    path: "{{ app_dir }}/monitoring/tempo/tempo.yml"
    state: absent

- name: Copy Tempo configuration
  copy:
    src: tempo.yml
    dest: "{{ app_dir }}/monitoring/tempo/tempo.yml"
    owner: root
    group: root
    mode: "0644"

- name: Remove incorrect Alloy config directory if present
  file:
    path: "{{ app_dir }}/monitoring/alloy/config.alloy"
    state: absent

- name: Copy Alloy configuration
  copy:
    src: alloy.alloy
    dest: "{{ app_dir }}/monitoring/alloy/config.alloy"
    owner: root
    group: root
    mode: "0644"
  notify: Restart application